In [66]:
import numpy as np

In [67]:
f = open("day_15.txt", "r")

In [68]:
lines = f.read().splitlines()

In [69]:
def numbers(line):
    return [int(char) for char in line]

In [70]:
numbers_mapped = map(numbers, lines)

In [71]:
grid = list(numbers_mapped)

In [72]:
print(np.matrix(grid))

[[1 1 6 3 7 5 1 7 4 2]
 [1 3 8 1 3 7 3 6 7 2]
 [2 1 3 6 5 1 1 3 2 8]
 [3 6 9 4 9 3 1 5 6 9]
 [7 4 6 3 4 1 7 1 1 1]
 [1 3 1 9 1 2 8 1 3 7]
 [1 3 5 9 9 1 2 4 2 1]
 [3 1 2 5 4 2 1 6 3 9]
 [1 2 9 3 1 3 8 5 2 1]
 [2 3 1 1 9 4 4 5 8 1]]
